---
title: "FR Y-9c Peer Banks Evaluation 2016-2018"
author: "Rob Carnell"
date: "November 7, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(rvest)
require(lubridate)
require(ggplot2)
require(assertthat)
require(pdftools)
require(RColorBrewer)
require(reshape2)
require(fry9c)

################################################################################

if (FALSE)
{
  X1Q18 <- get_fry9c_data(2018, 1)
  X2Q18 <- get_fry9c_data(2018, 2)
  X4Q17 <- get_fry9c_data(2017, 4)
  X3Q17 <- get_fry9c_data(2017, 3)
  X2Q17 <- get_fry9c_data(2017, 2)
  X1Q17 <- get_fry9c_data(2017, 1)
  X1Q16 <- get_fry9c_data(2016, 1)
  X2Q16 <- get_fry9c_data(2016, 2)
  X3Q16 <- get_fry9c_data(2016, 3)
  X4Q16 <- get_fry9c_data(2016, 4)
  X1Q15 <- get_fry9c_data(2015, 1)
  X2Q15 <- get_fry9c_data(2015, 2)
  X3Q15 <- get_fry9c_data(2015, 3)
  X4Q15 <- get_fry9c_data(2015, 4)
  
  save(X1Q18, X2Q18, 
       X4Q17, X3Q17, X2Q17, X1Q17,
       X4Q16, X3Q16, X2Q16, X1Q16,
       X4Q15, X3Q15, X2Q15, X1Q15,
       file = "fry9data.Rdata")
}
load("fry9data.Rdata")

fry9c_data_list <- list(X1Q16, X2Q16, X3Q16, X4Q16,
                        X1Q17, X2Q17, X3Q17, X4Q17,
                        X1Q18, X2Q18
                        )
rm(X1Q18, X2Q18, 
   X4Q17, X3Q17, X2Q17, X1Q17,
   X4Q16, X3Q16, X2Q16, X1Q16,
   X4Q15, X3Q15, X2Q15, X1Q15)

bank_meta_data <- get_bank_meta_data()

################################################################################
# Bank Info #

targets <- c("HUNTINGTON BANCSHARES INCORPORATED",
             "KEYCORP",
             "PNC BANK CORP",
             "JPMORGAN CHASE",
             "FIFTH THIRD BANCORP",
             "U.S. BANCORP",
             "M&T BANK",
             "BB&T CORPORATION",
             "REGIONS FINANCIAL CORPORATION",
             "SUNTRUST BANKS, INC")

targets_short <- c("HBAN", "KEY", "PNC", "JPM", "FITB", "USB", "MTB", "BBT",
                   "RF", "STI")
assertthat::assert_that(length(targets) == length(targets_short))

pal <- brewer.pal(9, "Set1")
stock_cols <- c("HBAN" = "Green", 
                "KEY" = pal[1], 
                "PNC" = pal[2], 
                "JPM" = pal[3], 
                "FITB" = pal[4], 
                "USB" = pal[5], 
                "MTB" = pal[6], 
                "BBT" = pal[7],
                "RF" = pal[8], 
                "STI" = pal[9])
assertthat::assert_that(length(targets) == length(stock_cols))
stock_sizes <- c("HBAN" = 3, 
                 "KEY" = 1, 
                 "PNC" = 1, 
                 "JPM" = 1, 
                 "FITB" = 1, 
                 "USB" = 1, 
                 "MTB" = 1, 
                 "BBT" = 1,
                 "RF" = 1, 
                 "STI" = 1)
assertthat::assert_that(length(targets) == length(stock_sizes))

################################################################################

target_ids <- get_bank_ids(targets, bank_meta_data)

fry9cs <- Fry9c_group(years = c(rep(2016, 4), rep(2017, 4), 2018, 2018),
                      quarters = c(1:4, 1:4, 1:2))

fry9cs$parse_fry9c(
  system.file(file.path("extdata", c(
  "FR_Y-9C20160331.xml", "FR_Y-9C20160630.xml", "FR_Y-9C20160930.xml",
  "FR_Y-9C20161231.xml", "FR_Y-9C20170331.xml", "FR_Y-9C20170630.xml",
  "FR_Y-9C20170930.xml", "FR_Y-9C20171231.xml", "FR_Y-9C20180331.xml",
  "FR_Y-9C20180630.xml"
)), package = "fry9c"))

fry9c_data_list_small <- lapply(fry9c_data_list, function(z) z[match(target_ids, z$RSSD9001),])
fry9cs$initializeData(fry9c_data_list_small, targets_short)

fry9cs$commonSize("HC-K", "5.", "HI")
fry9cs$commonSize("HC-K", "5.", "HI_Memo")

common_plots <- function(dat, nam)
{
  g1 <- ggplot(dat, aes(x = x, y = common_qdiff, group = bank, col = bank)) +
    geom_point(aes(size = bank)) +
    geom_line() + 
    scale_y_continuous(name = paste0(nam, " / Average Assets"), labels = scales::percent) +
    xlab("Quarter") +
    scale_color_manual(values = stock_cols) +
    scale_size_manual(values = stock_sizes)

  g2 <- ggplot(dat, aes(x = quarter, y = common_value, group = bank, col = bank)) +
    facet_grid(. ~ year) +
    geom_point(aes(size = bank)) +
    geom_line() + 
    scale_y_continuous(name = paste0("YTD ", nam, " / Average Assets"), labels = scales::percent) +
    xlab("Quarter") +
    scale_color_manual(values = stock_cols) +
    scale_size_manual(values = stock_sizes)

  g3 <- ggplot(subset(dat, year > 2016), 
             aes(x = quarter, y = common_yoy, group = bank, col = bank)) +
      facet_grid(. ~ year) +
      geom_point(aes(size = bank)) +
      geom_line() + 
      scale_y_continuous(name = paste0("YOY Growth in ", nam, " / Average Assets"), labels = scales::percent) +
      xlab("Quarter") +
      scale_color_manual(values = stock_cols) +
      scale_size_manual(values = stock_sizes)
  
  plot(g1)
  plot(g2)
  plot(g3)
}

```

## Average Assets

```{r average_assets, echo=FALSE}
asset_data <- fry9cs$get_plot_data("HC-K", "5.")

ggplot(asset_data, aes(x = x, y = value, group = bank, col = bank)) +
  geom_point(aes(size = bank)) +
  geom_line() + 
  scale_y_log10(name = "Total Assets (000s) (log scale)", labels = scales::dollar) +
  xlab("") +
  scale_color_manual(values = stock_cols) +
  scale_size_manual(values = stock_sizes)
```

## Interest Income

```{r interest_income, echo=FALSE}
interest_income_data <- fry9cs$get_plot_data("HI", "1.h.")
common_plots(interest_income_data, "Interest Income")
```

## Interest Expense

```{r interest_expense, echo=FALSE}
interest_expense_data <- fry9cs$get_plot_data("HI", "2.f.")
common_plots(interest_expense_data, "Interest Expense")
```

## Non-Interest Income

```{r non_interest_income, echo=FALSE}
noninterest_income_data <- fry9cs$get_plot_data("HI", "5.m.")
common_plots(interest_income_data, "Interest Income")
```

## Non-Interest Expense

```{r non_interest_expense, echo=FALSE}
noninterest_expense_data <- fry9cs$get_plot_data("HI", "7.e.")
common_plots(noninterest_expense_data, "non-Interest Expense")
```

## Marketing Expense

```{r marketing_expense, echo=FALSE}
marketing_expense_data <- fry9cs$get_plot_data("HI_Memo", "7.b.")
print(reshape2::dcast(marketing_expense_data, bank ~ x, value.var = "value"))

ggplot(subset(marketing_expense_data, bank == "HBAN"), aes(x = x, y = qdiff, group = bank, col = bank)) +
  geom_point() +
  geom_line() + scale_y_continuous(name = "Marketing Expense (000s)", labels = scales::dollar) +
  xlab("Quarter") +
  scale_color_manual(values = stock_cols)

ggplot(subset(marketing_expense_data, bank == "HBAN"), aes(x = quarter, y = value, group = bank, col = bank)) +
  facet_grid(. ~ year) +
  geom_point() +
  geom_line() + scale_y_continuous(name = "YTD Marketing Expense (000s)", labels = scales::dollar) +
  xlab("Quarter") +
  scale_color_manual(values = stock_cols)

common_plots(marketing_expense_data, "Marketing Expense")
```

## Data Expense

```{r data_expense, echo=FALSE}
data_expense_data <- fry9cs$get_plot_data("HI_Memo", "7.a.")
common_plots(data_expense_data, "Data Expense")
```

## Salary and Employee Benefits Expense

```{r employee_expense, echo=FALSE}
employee_expense_data <- fry9cs$get_plot_data("HI", "7.a.")
common_plots(employee_expense_data, "Employee Expense")
```

## Interchange Fee Income

```{r interchange_income, echo=FALSE}
interchange_income_data <- fry9cs$get_plot_data("HI_Memo", "6.f.")
common_plots(interchange_income_data, "Interchange Fee Income")
```

## Wire Transfer Income

```{r wire_income, echo=FALSE}
wire_income_data <- fry9cs$get_plot_data("HI_Memo", "6.g.")
common_plots(wire_income_data, "Wire Fee Income")
```
